// Module included in the following assemblies:
// * serverless-logic/serverless-logic-managing-supporting-services


:_mod-docs-content-type: REFERENCE
[id="serverless-logic-supporting-services-advanced-configuration_{context}"]
= Advanced supporting services configurations

[role="_abstract"]
In scenarios where you must apply advanced configurations for supporting services, use the `podTemplate` field in the `SonataFlowPlatform` custom resource (CR). This field allows you to customize the service pod deployment by specifying configurations like the number of replicas, environment variables, container images, resource requirements, and initialization options.

You can configure advanced settings for the service by using the following example:

.Advanced configurations example for the Data Index service
[source,yaml]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform-example
  namespace: example-namespace
spec:
  services:
    # This can be either 'dataIndex' or 'jobService'
    dataIndex:
      enabled: true
      podTemplate:
        replicas: 2
        container:
          env:
            - name: <any_advanced_config_property>
              value: <any_value>
          image:
          resources:
            limits:
              cpu:
              memory:
            requests:
              cpu:
              memory:
        initContainers:
----

[NOTE]
====
You can set the 'services' field to either 'dataIndex' or 'jobService' depending on your requirement. The rest of the configuration remains the same.
====

This configuration includes the following settings:

* `replicas` - Defines the number of replicas. Default value is `1`. In the case of `jobService`, this value is always overridden to `1` because it operates as a singleton service.
* `container` - Holds specific configurations for the container running the service.
* `env` - Allows you to fine-tune service properties by specifying environment variables.
* `image` - Configures the container image for the service, useful if you need to update or customize the image.
* `resources.limits.cpu` - Configures the CPU limit. Default value is `200m`.
* `resources.limits.memory` - Configures the memory limit. Default value is `1Gi`.
* `resources.requests.cpu` - Configures the CPU request. Default value is `100m`.
* `resources.requests.memory` - Configures the memory request. Default value is `1Gi`.
* `initContainers` - Configures init containers for the pod, useful for setting up prerequisites before the main container starts.

[NOTE]
====
The `podTemplate` field provides flexibility for tailoring the deployment of each supporting service. It follows the standard `PodSpec` API, meaning the same API validation rules apply to these fields.
====

[id="serverless-logic-supporting-services-autoscaling_{context}"]
== Configuring horizontal pod autoscaling for Data Index

You can configure horizontal pod autoscaling (HPA) for the Data Index service to automatically scale based on resource utilization. The Job Service does not support autoscaling because it operates as a singleton service.

.Prerequisites

* You have deployed a `SonataFlowPlatform` CR with the Data Index service enabled.
* You have configured resource requests for the Data Index service.

.Procedure

. Determine the Data Index deployment name:
+
The deployment name follows the pattern: `<sonataflowplatform-name>-data-index-service`.
+
For example, if your `SonataFlowPlatform` CR is named `sonataflow-platform-example`, the deployment name is `sonataflow-platform-example-data-index-service`.

. Create a `HorizontalPodAutoscaler` CR that targets the Data Index deployment:
+
[source,yaml]
----
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-index-example-autoscaler
  namespace: example-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sonataflow-platform-example-data-index-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
----
+
This configuration includes the following settings:
+
* `metadata.name` - Any name of your choice.
* `scaleTargetRef.name` - The calculated name of the Data Index deployment.
* `metrics` - Example metric based on CPU resource utilization.

. Apply the `HorizontalPodAutoscaler` configuration:
+
[source,terminal,subs="+quotes"]
----
$ *kubectl apply -f data-index-autoscaler.yaml -n example-namespace*
----

.Verification

* Verify that the HPA is configured correctly:
+
[source,terminal,subs="+quotes"]
----
$ *kubectl get hpa -n example-namespace*
----

[NOTE]
====
When the {ServerlessLogicOperatorName} detects a `HorizontalPodAutoscaler` targeting the Data Index deployment, replica management is delegated to the HPA controller. If you remove the `HorizontalPodAutoscaler`, the operator resumes control of replica management.
====

[NOTE]
====
You can configure the `HorizontalPodAutoscaler` metrics using any of the resource requests automatically configured by the {ServerlessLogicOperatorName}. The default resource values are:

[source,yaml]
----
resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
----

To modify these default values, configure the `resources` field in the `podTemplate` as shown in the advanced configurations example.
====

.Additional resources

* link:https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Horizontal Pod Autoscaling] in the Kubernetes documentation